server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: codezy-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: N1c@t_25192744
